name: Build and Push Image to ECR

on: 
  push:

jobs:
  login-toaws:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

  build-and-push-pub-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Login to AWS ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.ACCESS_KEY }}
          password: ${{ secrets.SECRET_ACCESS_KEY }}
        env:
          aws-region: ${{ secrets.REGION }}

      - name: Build Image
