name: Build and Push Image to ECR

on:
  workflow_dispatch:

jobs:
  build-and-push-pub-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Login to Public ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.ACCESS_KEY }}
          password: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Build Docker Image
        run: |
          docker build -t tm-comp .
          docker tag tm-comp:latest ${{ secrets.AWS_REPOSITORY }}/tm-comp:latest

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tm-comp:latest
          format: table
          exit-code: 0
          ignore-unfixed: true

      - name: Push Image to ECR
        run: |
          docker push ${{ secrets.AWS_REPOSITORY }}/tm-comp:latest
